# Generated by Django 4.0.2 on 2022-03-01 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sredmodel',
            name='author',
            field=models.CharField(default='shu', max_length=50),
            preserve_default=False,
        ),
    ]
