# Generated by Django 4.0.2 on 2022-02-26 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0002_rename_username_users_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_title', models.CharField(max_length=255, verbose_name='タイトル')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('delete_flg', models.SmallIntegerField(default=0, verbose_name='削除フラグ')),
            ],
        ),
        migrations.CreateModel(
            name='Msg_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg_detail', models.CharField(max_length=255, verbose_name='タイトル')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('delete_flg', models.SmallIntegerField(default=0, verbose_name='削除フラグ')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boardapp.board')),
            ],
        ),
    ]
