# Generated by Django 4.0.2 on 2022-02-26 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0003_board_msg_detail'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='users',
            new_name='User',
        ),
    ]
