# Generated by Django 4.0.2 on 2022-03-11 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0005_alter_sred_msg_post_create_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sred_msg_post', # モデル名
            old_name='create_at',   # 変更前
            new_name='created_at'    # 変更後
        )
    ]
