# Generated by Django 4.0.2 on 2022-03-11 22:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0006_auto_20220312_0656'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sred_msg_post',
            name='created_at',
        ),
        migrations.AddField(
            model_name='sred_msg_post',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 11, 22, 12, 9, 257171, tzinfo=utc), verbose_name='メッセージ送信日時'),
        ),
        migrations.AlterField(
            model_name='sredmodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 11, 22, 12, 9, 255007, tzinfo=utc), verbose_name='掲示板作成日時'),
        ),
    ]
